# Generated by Django 4.2.3 on 2023-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Class',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
