# Generated by Django 4.2.3 on 2023-07-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HApp', '0002_doctor_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Amount', models.FloatField()),
                ('Doctor_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HApp.doctor')),
            ],
        ),
    ]
