# Generated by Django 4.2.3 on 2023-07-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HApp', '0003_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='Customer_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
